import type { Building } from "./types";

export const buildings: Building[] = [
	{
		name: "huts",
		image: "tipi.png",
		prereq: "unlockHuts",
		cost: [{ resource: "food", amount: 1 }],
		resourceLimitModifier: [{ resource: "villagers", amount: 2, type: "add" }],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	{
		name: "farms",
		image: "barn.png",
		prereq: "unlockFarming",
		cost: [{ resource: "lumber", amount: 1 }],
		resourceLimitModifier: [],
		bonus: [{ resource: "food", amount: 0.05 }],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	{
		name: "lumberMills",
		image: "circular-saw.png",
		prereq: "unlockWoodConstruction",
		cost: [{ resource: "lumber", amount: 2 }],
		resourceLimitModifier: [],
		bonus: [{ resource: "lumber", amount: 0.1 }],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	{
		name: "storerooms",
		image: "block-house.png",
		prereq: "unlockStoneConstruction",
		cost: [{ resource: "lumber", amount: 5 }],
		resourceLimitModifier: [
			{ resource: "food", amount: 5, type: "add" },
			{ resource: "lumber", amount: 5, type: "add" },
			{ resource: "stone", amount: 5, type: "add" },
		],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	{
		name: "quarries",
		image: "gold-mine.png",
		prereq: "unlockStoneConstruction",
		cost: [{ resource: "lumber", amount: 2 }],
		resourceLimitModifier: [],
		bonus: [{ resource: "stone", amount: 0.06 }],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	{
		name: "schools",
		image: "graduate-cap.png",
		prereq: "unlockSchools",
		cost: [{ resource: "lumber", amount: 3 }],
		resourceLimitModifier: [],
		bonus: [{ resource: "research", amount: 0.06 }],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	{
		name: "libraries",
		image: "book-cover.png",
		prereq: "unlockLibraries",
		cost: [{ resource: "lumber", amount: 4 }],
		resourceLimitModifier: [{ resource: "research", amount: 5, type: "add" }],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	{
		name: "huntingCamps",
		image: "watch.png",
		prereq: "unlockHunting",
		cost: [{ resource: "lumber", amount: 2 }],
		resourceLimitModifier: [],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	{
		name: "smithies",
		image: "watch.png",
		prereq: "unlockSmithies",
		cost: [{ resource: "lumber", amount: 3 }],
		resourceLimitModifier: [],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
];
