import type { Building, Game } from "./types";

export const buildings: Record<keyof Game["buildings"], Building> = {
	huts: {
		name: "huts",
		image: "tentTree",
		prereq: "unlockHuts",
		cost: [{ resource: "food", amount: 1 }],
		resourceLimitModifier: [{ resource: "villagers", amount: 2, type: "add" }],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	farms: {
		name: "farms",
		image: "tractor",
		prereq: "unlockFarming",
		cost: [{ resource: "lumber", amount: 1 }],
		resourceLimitModifier: [],
		bonus: [{ resource: "food", amount: 0.05 }],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	lumberMills: {
		name: "lumberMills",
		image: "treeDeciduous",
		prereq: "unlockWoodConstruction",
		cost: [{ resource: "lumber", amount: 2 }],
		resourceLimitModifier: [],
		bonus: [{ resource: "lumber", amount: 0.1 }],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	storerooms: {
		name: "storerooms",
		image: "box",
		prereq: "unlockStoneConstruction",
		cost: [{ resource: "lumber", amount: 5 }],
		resourceLimitModifier: [
			{ resource: "food", amount: 5, type: "add" },
			{ resource: "lumber", amount: 5, type: "add" },
			{ resource: "stone", amount: 5, type: "add" },
		],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	quarries: {
		name: "quarries",
		image: "mountainSnow",
		prereq: "unlockStoneConstruction",
		cost: [{ resource: "lumber", amount: 2 }],
		resourceLimitModifier: [],
		bonus: [{ resource: "stone", amount: 0.06 }],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	schools: {
		name: "schools",
		image: "school",
		prereq: "unlockSchools",
		cost: [{ resource: "lumber", amount: 3 }],
		resourceLimitModifier: [],
		bonus: [{ resource: "research", amount: 0.06 }],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	libraries: {
		name: "libraries",
		image: "squareLibrary",
		prereq: "unlockLibraries",
		cost: [{ resource: "lumber", amount: 4 }],
		resourceLimitModifier: [{ resource: "research", amount: 5, type: "add" }],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	huntingCamps: {
		name: "huntingCamps",
		image: "tent",
		prereq: "unlockNever",
		cost: [{ resource: "food", amount: 2 }],
		resourceLimitModifier: [],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
	smithies: {
		name: "smithies",
		image: "anvil",
		prereq: "unlockNever",
		cost: [{ resource: "lumber", amount: 3 }],
		resourceLimitModifier: [],
		bonus: [],
		status: "hidden",
		amount: 0,
		sellable: false,
	},
};
