import {
	Anvil,
	Axe,
	Bean,
	Bed,
	Box,
	Boxes,
	BrickWall,
	Briefcase,
	BriefcaseMedical,
	Building,
	Castle,
	Church,
	Circle,
	CircleOff,
	DraftingCompass,
	Drill,
	Factory,
	Fence,
	Flame,
	FlaskConical,
	Gavel,
	GraduationCap,
	Hammer,
	HardHat,
	Hospital,
	House,
	Library,
	Mountain,
	Music,
	Package,
	Paintbrush,
	Pickaxe,
	School,
	Shovel,
	Sword,
	Telescope,
	Tent,
	TentTree,
	Tractor,
	TreeDeciduous,
	TreePine,
	Users,
	Wheat,
	Wrench,
} from "lucide-react";

export const ICONS = {
	// resources
	wheat: { Icon: Wheat, color: "text-yellow-500" },
	treePine: { Icon: TreePine, color: "text-green-500" },
	mountain: { Icon: Mountain, color: "text-stone-500" },
	flaskConical: { Icon: FlaskConical, color: "text-blue-500" },
	users: { Icon: Users, color: "text-slate-500" },

	// villagers
	bed: { Icon: Bed, color: "text-neutral-500" },
	shovel: { Icon: Shovel, color: "text-neutral-500" },
	graduationCap: { Icon: GraduationCap, color: "text-neutral-500" },
	telescope: { Icon: Telescope, color: "text-neutral-500" },
	axe: { Icon: Axe, color: "text-neutral-500" },
	pickaxe: { Icon: Pickaxe, color: "text-neutral-500" },
	hammer: { Icon: Hammer, color: "text-neutral-500" },
	drill: { Icon: Drill, color: "text-neutral-500" },
	wrench: { Icon: Wrench, color: "text-neutral-500" },
	anvil: { Icon: Anvil, color: "text-neutral-500" },
	draftingCompass: { Icon: DraftingCompass, color: "text-neutral-500" },
	gavel: { Icon: Gavel, color: "text-neutral-500" },
	paintbrush: { Icon: Paintbrush, color: "text-neutral-500" },
	sword: { Icon: Sword, color: "text-neutral-500" },
	briefcase: { Icon: Briefcase, color: "text-neutral-500" },
	briefcaseMedical: { Icon: BriefcaseMedical, color: "text-neutral-500" },
	music: { Icon: Music, color: "text-neutral-500" },

	// technologies

	bean: { Icon: Bean, color: "text-yellow-700" },
	circle: { Icon: Circle, color: "text-neutral-500" },
	fence: { Icon: Fence, color: "text-neutral-300" },
	brickWall: { Icon: BrickWall, color: "text-neutral-500" },
	flame: { Icon: Flame, color: "text-orange-400" },
	circleOff: { Icon: CircleOff, color: "text-orange-400" },

	// buildings
	tent: { Icon: Tent, color: "text-yellow-600" },
	tentTree: { Icon: TentTree, color: "text-neutral-500" },
	tractor: { Icon: Tractor, color: "text-red-500" },
	treeDeciduous: { Icon: TreeDeciduous, color: "text-green-500" },
	box: { Icon: Box, color: "text-yellow-600" },
	boxes: { Icon: Boxes, color: "text-yellow-600" },
	package: { Icon: Package, color: "text-yellow-600" },
	hardHat: { Icon: HardHat, color: "text-yellow-400" },
	library: { Icon: Library, color: "text-neutral-500" },
	house: { Icon: House, color: "text-neutral-500" },
	building: { Icon: Building, color: "text-neutral-500" },
	school: { Icon: School, color: "text-neutral-500" },
	castle: { Icon: Castle, color: "text-neutral-500" },
	church: { Icon: Church, color: "text-neutral-500" },
	factory: { Icon: Factory, color: "text-neutral-500" },
	hospital: { Icon: Hospital, color: "text-neutral-500" },
};
